### ISSUE TITLE
Symbol not found: _BrotliDecoderCreateInstance with Python 3.7.2 and fresh pip install

### ISSUE THREAD

**Issue by pirate** [python-hyper/brotlipy#146]
There seems to be something preventing brotlipy from working on my machine:

```bash
$ pip --version
pip 19.0.1
$ virtualenv -p $(which python3.7) venv
$ source venv/bin/activate
$ python --version
Python 3.7.2
```
```bash
$ pip install --no-deps --no-binary :all: --ignore-installed brotlipy
Collecting brotlipy
  Using cached https://files.pythonhosted.org/packages/d9/91/bc79b88590e4f662bd40a55a2b6beb0f15da4726732efec5aa5a3763d856/brotlipy-0.7.0.tar.gz
Skipping bdist_wheel for brotlipy, due to binaries being disabled for it.
Installing collected packages: brotlipy
  Running setup.py install for brotlipy ... done
Successfully installed brotlipy-0.7.0
```
```python
$ python
>>> import brotli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/test/venv/lib/python3.7/site-packages/brotli/__init__.py", line 3, in <module>
    from .brotli import (
  File "~/test/venv/lib/python3.7/site-packages/brotli/brotli.py", line 5, in <module>
    from ._brotli import ffi, lib
ImportError: dlopen(~/test/venv/lib/python3.7/site-packages/brotli/_brotli.abi3.so, 2): Symbol not found: _BrotliDecoderCreateInstance
  Referenced from: ~/test/venv/lib/python3.7/site-packages/brotli/_brotli.abi3.so
  Expected in: flat namespace
 in ~/test/venv/lib/python3.7/site-packages/brotli/_brotli.abi3.so
```

This also happens with just plain `pip install`.

**Comment by kukat** [comment]
same error

**Comment by pirate** [comment]
IIRC @ikreymer just ended up disabling brotli support in pywb when this error is encountered, so unfortunately I don't know of any workaround at the moment @kukat. Please post back if you do find a way to fix this!

**Comment by paucky** [comment]
I use anaconda py3.6 / ubuntu
The finial solution
apt-get install python3-cffi-backend
